### ISSUE TITLE
Suggestion: Add descriptions for each section of the HTML and CSS to improve readability.

### ISSUE THREAD

**Issue by josephtkim** [laura-313/teacozy#6]
It's always a good idea to add descriptions above each section of code, to make each major section more distinguishable. 

For the HTML, you might have
```html
<!-- Footer Section -->
<footer>
  <h2>The Tea Cozy</h2>
  <h5>contact@theteacozy.com</h5>
  <h5>917-555-8904</h5>
</footer>

<!-- Copyright Section -->
<h5 class="copyright">copyright The Tea Cozy 2017</h5>
```

For the CSS, you might have
```css
/* Footer Section */
footer {
  width: 1200px;
  height: 200px;
  display: flex;
  flex-direction: column;
  margin: auto;
  justify-content: flex-start;
}

/* Copyright Section */
.copyright {
  padding-left: 20px;
    text-align: left;
}
```
